### ISSUE TITLE
Compile without Roswell

### ISSUE THREAD

**Issue by observant2** [fukamachi/sblint#8]
On Windows 10 I cannot install roswell and I have set up my lisp environment + emacs quite well, so I also don't want to install it.

How can I compile sblint to an executable myself? I cannot seem to find the main function.

**Comment by jonatack** [comment]
Yes. Same situation on Linux Debian.

**Comment by fukamachi** [comment]
sblint supports only Roswell for now because lack of time to do it.


2019年7月17日(水) 1:32 Jon Atack <notifications@github.com>:

**Comment by vindarel** [comment]
> I cannot seem to find the main function.

See https://github.com/fukamachi/sblint/blob/master/roswell/sblint.ros

There occurs the parsing of CLI args (nothing fancy, there are only two), and the call of sblint. 

The `main` function receives a list of the arguments:

    (defun main (&rest argv)

Roswell gives this `argv`. In SBCL, they are stored in `sb-ext:*posix-argv*` (https://lispcookbook.github.io/cl-cookbook/scripting.html#parsing-command-line-arguments). 

So, at first glance, you could write an entry point into the asd file to build a binary (`asdf:make`, https://lispcookbook.github.io/cl-cookbook/scripting.html#with-asdf), which would call the `main` with the list of CLI args. You might need to move the `main` to a proper .lisp file.

hope that helps.
